MPESA_CONSUMER_KEY: '66y2FmHpuddAVGOHAwHrA2TYfKyIxn6v'
MPESA_CONSUMER_SECRET: 'RyvJoKrSPfeM8Mgy'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORTCODE: '174379'
MPESA_INITIATOR_NAME: 'react-rails-mpesa'
MPESA_INITIATOR_PASSWORD: '<your initiator password>'
CALLBACK_URL: 'https://mydomain.com/path'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"